CREATE TABLE examadmin ( myid serial NOT NULL, mytitle character varying(255), mystart timestamp without time zone, myend timestamp without time zone, myitemno integer, mystatus character(1) DEFAULT 'E'::bpchar NOT NULL, CONSTRAINT examadmin_check CHECK ((myend > mystart)));
CREATE TABLE examgroup ( myid serial NOT NULL, examid integer, groupid integer);
CREATE TABLE examitem ( examid integer NOT NULL, itemid integer NOT NULL, groupid integer, examorder smallint);
CREATE TABLE examstudent ( myid serial NOT NULL, examid integer NOT NULL, studentid character(10), stdstatus character(1) DEFAULT 'N'::bpchar NOT NULL);
CREATE TABLE examsubmit ( myid serial NOT NULL, examid integer NOT NULL, userid character(10) NOT NULL, itemid integer, iscorrect character(1) DEFAULT 0 NOT NULL, submittime timestamp without time zone DEFAULT now() NOT NULL, answered varchar(100) );
CREATE TABLE examsubmit2 ( examid integer NOT NULL, userid character(10) NOT NULL, itemid integer NOT NULL, iscorrect character(1) DEFAULT 0 NOT NULL, submittime timestamp without time zone DEFAULT now() NOT NULL);
CREATE TABLE itemainfotable ( myid serial NOT NULL, itemid integer, myformat character(1), mycategory character(2), mylevel character(1), mysubject character(2), mymesh character varying(255), mycase character(1), mytype character(1) DEFAULT 'A'::bpchar NOT NULL);
CREATE TABLE itemginfotable ( itemid integer NOT NULL, groupid integer, grouporder smallint);
CREATE TABLE itemgrouptable ( myid serial NOT NULL, mytext text, isindep character(1) DEFAULT 'N'::bpchar, myimage character varying(255), mymovie character varying(255));
CREATE TABLE itemtable ( myid serial NOT NULL, mytest text, mycorrect text, myscore smallint, isobject character(1) DEFAULT 'N'::bpchar);
CREATE TABLE objecttable ( myid serial NOT NULL, itemid integer NOT NULL, myfile character varying(255) NOT NULL);
CREATE TABLE optiontable ( myid serial NOT NULL, itemid integer, myorder smallint, mytext character varying(255), myimage character varying(255));
CREATE TABLE sessions ( session_key character(32) NOT NULL, session_expire bigint, session_value text);
CREATE TABLE staffinfo ( myid character(10) NOT NULL, mypassword character(32), mylevel character(1), myscode character(2), myname character varying(30), myposition character varying(20), myrno1 character(6), myemail character varying(50));
CREATE TABLE univinfo ( mycode character(2) NOT NULL, mytitle character varying(40) NOT NULL);
CREATE TABLE univstudent ( univid character(2) NOT NULL, univsno character varying(15) NOT NULL, studname character varying(30), studdept character varying(30), studgrade character(1), studtel character varying(14), studrno1 character(6), studeemail character varying(50), mylevel character(1) DEFAULT 'B'::bpchar NOT NULL);
CREATE TABLE userinfo ( myid character(10) NOT NULL, mypassword character(32), univid character(2), univsno character varying(15));
ALTER TABLE ONLY examadmin ADD CONSTRAINT eapk1 PRIMARY KEY (myid);
ALTER TABLE ONLY examgroup ADD CONSTRAINT egpk1 PRIMARY KEY (myid);
ALTER TABLE ONLY examitem ADD CONSTRAINT eipk1 PRIMARY KEY (examid, itemid);
ALTER TABLE ONLY examsubmit2 ADD CONSTRAINT es2_pk PRIMARY KEY (examid, userid, itemid);
ALTER TABLE ONLY examsubmit ADD CONSTRAINT es_pk PRIMARY KEY (myid);
ALTER TABLE ONLY examstudent ADD CONSTRAINT espk1 PRIMARY KEY (myid);
ALTER TABLE ONLY itemainfotable ADD CONSTRAINT iai_pk PRIMARY KEY (myid);
ALTER TABLE ONLY itemgrouptable ADD CONSTRAINT igtpk1 PRIMARY KEY (myid);
ALTER TABLE ONLY itemginfotable ADD CONSTRAINT iitpk1 PRIMARY KEY (itemid);
ALTER TABLE ONLY itemtable ADD CONSTRAINT itpk1 PRIMARY KEY (myid);
ALTER TABLE ONLY objecttable ADD CONSTRAINT obj_pk PRIMARY KEY (myid);
ALTER TABLE ONLY optiontable ADD CONSTRAINT opt_pk PRIMARY KEY (myid);
ALTER TABLE ONLY sessions ADD CONSTRAINT sess_pk1 PRIMARY KEY (session_key);
ALTER TABLE ONLY staffinfo ADD CONSTRAINT si_pk1 PRIMARY KEY (myid);
ALTER TABLE ONLY userinfo ADD CONSTRAINT ui_pk1 PRIMARY KEY (myid);
ALTER TABLE ONLY univinfo ADD CONSTRAINT uipk PRIMARY KEY (mycode);
ALTER TABLE ONLY univstudent ADD CONSTRAINT us_pk1 PRIMARY KEY (univid, univsno);
ALTER TABLE ONLY examgroup ADD CONSTRAINT egfk1 FOREIGN KEY (examid) REFERENCES examadmin(myid) ON DELETE CASCADE;
ALTER TABLE ONLY examitem ADD CONSTRAINT eifk1 FOREIGN KEY (itemid) REFERENCES itemtable(myid) ON DELETE CASCADE;
ALTER TABLE ONLY examitem ADD CONSTRAINT eifk2 FOREIGN KEY (examid) REFERENCES examadmin(myid) ON DELETE CASCADE;
ALTER TABLE ONLY examsubmit2 ADD CONSTRAINT es2_fk1 FOREIGN KEY (examid) REFERENCES examadmin(myid) ON UPDATE CASCADE;
ALTER TABLE ONLY examsubmit2 ADD CONSTRAINT es2_fk2 FOREIGN KEY (userid) REFERENCES userinfo(myid) ON UPDATE CASCADE;
ALTER TABLE ONLY examsubmit2 ADD CONSTRAINT es2_fk3 FOREIGN KEY (itemid) REFERENCES itemtable(myid) ON UPDATE CASCADE;
ALTER TABLE ONLY examsubmit ADD CONSTRAINT es_fk1 FOREIGN KEY (examid) REFERENCES examadmin(myid) ON UPDATE CASCADE;
ALTER TABLE ONLY examsubmit ADD CONSTRAINT es_fk2 FOREIGN KEY (userid) REFERENCES userinfo(myid) ON UPDATE CASCADE;
ALTER TABLE ONLY examsubmit ADD CONSTRAINT es_fk3 FOREIGN KEY (itemid) REFERENCES itemtable(myid) ON UPDATE CASCADE;
ALTER TABLE ONLY examstudent ADD CONSTRAINT esfk1 FOREIGN KEY (examid) REFERENCES examadmin(myid) ON DELETE CASCADE;
ALTER TABLE ONLY examstudent ADD CONSTRAINT esfk2 FOREIGN KEY (studentid) REFERENCES userinfo(myid) ON DELETE CASCADE;
ALTER TABLE ONLY itemainfotable ADD CONSTRAINT iai_fk FOREIGN KEY (itemid) REFERENCES itemtable(myid);
ALTER TABLE ONLY itemginfotable ADD CONSTRAINT iitfk2 FOREIGN KEY (itemid) REFERENCES itemtable(myid) ON DELETE CASCADE;
ALTER TABLE ONLY objecttable ADD CONSTRAINT obj_fk FOREIGN KEY (itemid) REFERENCES itemtable(myid);
ALTER TABLE ONLY optiontable ADD CONSTRAINT opt_fk FOREIGN KEY (itemid) REFERENCES itemtable(myid);
ALTER TABLE ONLY staffinfo ADD CONSTRAINT si_fk1 FOREIGN KEY (myscode) REFERENCES univinfo(mycode) ON UPDATE CASCADE;
ALTER TABLE ONLY userinfo ADD CONSTRAINT ui_fk1 FOREIGN KEY (univid, univsno) REFERENCES univstudent(univid, univsno);
ALTER TABLE ONLY univstudent ADD CONSTRAINT us_fk1 FOREIGN KEY (univid) REFERENCES univinfo(mycode) ON UPDATE CASCADE;
